spring:
  application:
    name: "events-db-service"
  datasource:
    url: "jdbc:postgresql://events-db:5432/events-db"
    driver-class-name: "org.postgresql.Driver"
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"
logging:
  level:
    org:
      springframework:
        jdbc: DEBUG